# Prose Pod API
# REST API for administrating a Prose Pod
# Configuration file
# Example: https://github.com/prose-im/prose-pod-system/blob/master/Prose-example.toml
# All keys: https://github.com/prose-im/prose-pod-api/blob/master/crates/service/src/features/app_config/mod.rs

[branding]
page_url = "http://admin.prose.org.local/"
company_name = "Prose (local)"

[databases.main]
url = "sqlite://database.sqlite?mode=rwc"

[notify.email]
pod_address = "pod@prose.org.local"

smtp_host = "mailpit"
smtp_encrypt = false

[debug_only]
automatically_accept_invitations = true
insecure_password_on_auto_accept_invitation = true

[debug_only.dependency_modes]
notifier = "logging"
