name: prose-pod-api-local
services:
  api:
    image: "${PROSE_POD_API_IMAGE:-proseim/prose-pod-api:${PROSE_POD_API_IMAGE_TAG:-unknown}}"
    depends_on:
      - server
      - coredns
      - mailpit
    ports:
      - "8080:8080"
    volumes:
      - "${DATABASE_PATH:-./database.sqlite}:/database.sqlite"
      - "${PROSE_CONFIG_FILE:-./Prose.toml}:/Prose.toml"
      - "${ETC_PROSODY_DIR:?}:/etc/prosody/"
    networks: [prose-network]
    environment:
      RUST_LOG_STYLE: always
    env_file: "${ENV_FILE:-./local-run.env}"
    dns: 172.20.0.42

  # https://github.com/prose-im/prose-pod-server
  server:
    image: "${PROSE_POD_SERVER_IMAGE:-proseim/prose-pod-server:${PROSE_POD_SERVER_IMAGE_TAG:-unknown}}"
    volumes:
      - "${ETC_PROSODY_DIR:?}:/etc/prosody/"
      - "${VAR_LIB_PROSODY_DIR:?}:/var/lib/prosody/"
    networks:
      prose-network:
        aliases:
          - prose-pod-server
          - prose-pod-server-admin
          - prose.org.local
        ipv4_address: 172.20.0.40
        ipv6_address: 2001:db8::40
    env_file: "${ENV_FILE:-./local-run.env}"
    entrypoint: >
      sh -c "cp /etc/prosody/prosody.initial.cfg.lua /etc/prosody/prosody.cfg.lua && prosody"

  # https://github.com/coredns/coredns
  coredns:
    image: coredns/coredns:latest
    volumes:
      - ${COREDNS_COREFILE:-./coredns/Corefile}:/etc/coredns/Corefile
      - ${DNS_ZONE_FILE:-./dns-zones/default.zone}:/etc/coredns/zones.db
    command: ["-conf", "/etc/coredns/Corefile"]
    networks:
      prose-network:
        ipv4_address: 172.20.0.42

  # https://github.com/axllent/mailpit
  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025" # Web UI
    environment:
      MP_SMTP_AUTH_ALLOW_INSECURE: true
      MP_SMTP_BIND_ADDR: 0.0.0.0:587
    networks:
      prose-network:
        aliases:
          - mailpit

networks:
  prose-network:
    name: Prose Pod API local run network
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.20.0.0/24
        - subnet: 2001:db8::/64
