name: prose-pod-api-local
services:
  api:
    image: "${PROSE_POD_API_IMAGE:-proseim/prose-pod-api:${PROSE_POD_API_IMAGE_TAG:-unknown}}"
    depends_on:
      - server
      - coredns
      - mailpit
    ports:
      - "8080:8080"
    volumes:
      - "${DATABASE_PATH:?}:/var/lib/prose-pod-api/database.sqlite"
      - "${PROSE_CONFIG_FILE:?}:/etc/prose-pod-api/Prose.toml"
      - "${ETC_PROSODY_DIR:?}:/etc/prosody/"
    networks: [prose-network]
    env_file: "${ENV_FILE:?}"
    dns: 172.20.0.42
    # Make sure logs are colored.
    tty: true

  # https://github.com/prose-im/prose-pod-server
  server:
    image: "${PROSE_POD_SERVER_IMAGE:-proseim/prose-pod-server:${PROSE_POD_SERVER_IMAGE_TAG:-unknown}}"
    volumes:
      - "${ETC_PROSODY_DIR:?}:/etc/prosody/"
      - "${VAR_LIB_PROSODY_DIR:?}:/var/lib/prosody/"
    networks:
      prose-network:
        aliases:
          - prose-pod-server
          - prose-pod-server-admin
          - "${SERVER_DOMAIN:?}"
        ipv4_address: 172.20.0.40
        ipv6_address: 2001:db8::40
    env_file: "${ENV_FILE:?}"
    entrypoint: >
      sh -c "cp /etc/prosody/prosody.initial.cfg.lua /etc/prosody/prosody.cfg.lua && prosody"
    # Make sure logs are colored.
    tty: true

  # https://github.com/coredns/coredns
  coredns:
    image: coredns/coredns:latest
    volumes:
      - ${COREDNS_COREFILE:?}:/etc/coredns/Corefile
      - ${DNS_ZONE_FILE:?}:/etc/coredns/zones.db
    command: ["-conf", "/etc/coredns/Corefile"]
    networks:
      prose-network:
        ipv4_address: 172.20.0.42
    # Make sure logs are colored.
    tty: true

  # https://github.com/axllent/mailpit
  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025" # Web UI
    volumes:
      - "${MAILPIT_DATABASE_PATH:?}:/var/lib/mailpit/database.db"
    environment:
      MP_SMTP_AUTH_ALLOW_INSECURE: true
      MP_SMTP_BIND_ADDR: 0.0.0.0:587
      MP_DATABASE: /var/lib/mailpit/database.db
    networks:
      prose-network:
        aliases:
          - mailpit
    # Make sure logs are colored.
    tty: true

networks:
  prose-network:
    name: Prose Pod API local run network
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.20.0.0/24
        - subnet: 2001:db8::/64
