service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger, zipkin, otlp/signoz, otlp/lgtm]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/signoz, otlp/lgtm]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/signoz, otlp/lgtm]
  telemetry:
    logs:
      level: debug

# NOTE: See [Configuration | OpenTelemetry](https://opentelemetry.io/docs/collector/configuration/#receivers)
#   and [opentelemetry-collector/receiver/README.md at main · open-telemetry/opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-collector/blob/main/receiver/README.md#configuring-receivers)
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

# NOTE: See [Configuration | OpenTelemetry](https://opentelemetry.io/docs/collector/configuration/#exporters)
#   and [opentelemetry-collector/exporter/exporterhelper/README.md at main · open-telemetry/opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/exporterhelper/README.md#configuration).
exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans
    format: proto
    tls:
      insecure: true
  otlp/signoz:
    endpoint: signoz-otel-collector:4317
    tls:
      insecure: true
  otlp/lgtm:
    endpoint: otel-lgtm:4317
    tls:
      insecure: true
